In [2]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
from scipy import integrate

In [3]:
n = 5
Roots, Weights = np.polynomial.legendre.leggauss(n)
Roots,Weights

(array([-0.90617985, -0.53846931,  0.        ,  0.53846931,  0.90617985]),
 array([0.23692689, 0.47862867, 0.56888889, 0.47862867, 0.23692689]))

In [5]:
n = 20
Roots,Weights = np.polynomial.laguerre.laggauss(n)
Roots

array([ 0.07053989,  0.37212682,  0.9165821 ,  1.70730653,  2.74919926,
        4.04892531,  5.61517497,  7.45901745,  9.59439287, 12.03880255,
       14.81429344, 17.94889552, 21.47878824, 25.45170279, 29.93255463,
       35.01343424, 40.83305706, 47.61999405, 55.81079575, 66.52441653])